# Project Information
site_name: JailMan
site_description: 'Project Documentation for JailManager'
site_author: 'JailManager Team'
site_url: 'https://jailmanager.org'

# Repository
repo_name: 'jailmanager/wiki'
repo_url: 'jailmanager/wiki'
edit_uri: 'edit/dev/docs/'

theme:
  name: 'material'
  features:
    - tabs
  language: 'en'
    
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true